spring:
  jms:
    servicebus:
      connection-string: "Endpoint=sb://liondance0518.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=OStab/7t8pg0aVbh/TlZdSNSo5nkkFmEe9Dzuwa+WT0="
      topic-client-id: "09324699-18ab-40e7-aa98-655d9dab09c4"
      pricing-tier: "Standard"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



azure:
  service-bus:
    meeting:
      connection-string: "Endpoint=sb://liondance0518.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=OStab/7t8pg0aVbh/TlZdSNSo5nkkFmEe9Dzuwa+WT0="
      queue-name: "meeting"
    test:
      connection-string: "Endpoint=sb://liondance0518.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=OStab/7t8pg0aVbh/TlZdSNSo5nkkFmEe9Dzuwa+WT0="
      queue-name: "azuretest"